apiVersion: v1
kind: Secret
metadata:
  name: fiap-video-processing-secret
  namespace: default
  labels:
    app: fiap-app-video
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${BASE64_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: ${BASE64_SESSION_TOKEN}
