name: CI/CD - Pipeline de Deploy EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: eks-fiap-soat10
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ECR_NAME: file-processing-api
  SQS_PAYMENT_QUEUE_URL: ${{ secrets.SQS_PAYMENT_QUEUE_URL }}
  SNS_PAYMENT_TOPIC_ARN: ${{ secrets.SNS_PAYMENT_TOPIC_ARN }}

jobs:
  deploy:
    name: Deploy EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        run: |
          aws ecr get-login-password \
          --region us-west-2 | \
          docker login --username AWS \
          --password-stdin \
          381492156649.dkr.ecr.us-west-2.amazonaws.com

      - name: BuildAndPush Dockerfile
        run: |
          docker build -t file-processing-api . && \
          docker tag file-processing-api:latest 381492156649.dkr.ecr.us-west-2.amazonaws.com/file-processing-api:latest && \
          docker push 381492156649.dkr.ecr.us-west-2.amazonaws.com/file-processing-api:latest

      - name: Update Kube Config
        run: |
          aws eks update-kubeconfig \
          --name eks-fiap-soat10 \
          --region us-west-2

      - name: Kube Apply
        env:
          IMAGE: 381492156649.dkr.ecr.us-west-2.amazonaws.com/file-processing-api:latest
        run: |
          envsubst < k8s/configmap.yaml
          envsubst < k8s/configmap.yaml | kubectl apply -f -
          export BASE64_ACCESS_KEY_ID=$(echo -n "${{ secrets.AWS_ACCESS_KEY_ID }}" | base64 -w 0)
          export BASE64_SECRET_ACCESS_KEY=$(echo -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | base64 -w 0)
          export BASE64_SESSION_TOKEN=$(echo -n "${{ secrets.AWS_SESSION_TOKEN }}" | base64 -w 0)
          envsubst < k8s/secret.yaml
          envsubst < k8s/secret.yaml | kubectl apply -f -
          envsubst < k8s/deployment-app.yaml | kubectl apply -f -
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml
